### ISSUE TITLE
Make debug message "DEBUG: add url" more informative

### ISSUE THREAD

**Issue by kristiank** [spraakbanken/karp-backend-v5#1]
When I start the backend with `python backend.wsgi` it throws "DEBUG: add url" (appr. 20 times).

I know I haven't set up the dummyauth module and probably left out doing a bunch of things, so this Issue is more a request to make the debug message more informative.

**Comment by kristiank** [comment]
I tracked the source of the message: line 93 in file `src/server/helper/flaskhelper.py`

**Comment by kristiank** [comment]
... and it does not seem to be connected to the dummyouth, but you probably know this allready :-)

**Comment by MalinAhlberg** [comment]
This is very much just a debug message, not relevant for most people. It's saying that the urls from `backend.py` has been found and will be used.There are a number of such debug messages at the moment, you probably don't need to bother about any of them.

I will remove/clearify this message.

**Comment by kristiank** [comment]
So this is not a problem for me? I should just ignore it?

**Comment by MalinAhlberg** [comment]
No, not a problem for you :) Warnings and exceptions would be a problem, debug messages should not.
