### ISSUE TITLE
Autocomplete-anropet fungerar inte som förväntat

### ISSUE THREAD

**Issue by kod-kristoff** [spraakbanken/karp-backend-v5#13]
Autocomplete-anropet fungerar inte som förväntat i v5. Svaret
ger alldeles för många träffar. Jämför sökning efter “hatt” som ska ge
lemgram som innehåller strängen “hatt”:
[v5](https://ws.spraakbanken.gu.se/ws/karp/v5/autocomplete?q=hatt&resource=saldomp&mode=external)
[v4](https://ws.spraakbanken.gu.se/ws/karp/v4/autocomplete?q=hatt&resource=saldom&mode=external)
I v4-exemplet syns det väntade svaret. Det är också oklart vad skillnaden
mellan resurserna saldom och saldomp är.

**Comment by anne17** [comment]
Lemgramen i resultatet ska förstås innehålla strängen "hatt" (inte katt). My bad...

**Comment by kod-kristoff** [comment]
Issue moved to [spraakbanken/karp-backend-sb #18](https://github.com/spraakbanken/karp-backend-sb/issues/18) via [**ZenHub**](https://www.zenhub.com/)
