### ISSUE TITLE
Elasticsearch seems to be not available

### ISSUE THREAD

**Issue by kristiank** [spraakbanken/karp-backend-v5#3]
I now should have all the configuration done and start getting new errors. From what I can understand of the log file, the elasticsearch service is not available `WARNING: PUT http://elasticsearch:9200/karp_test [status:N/A request:0.069s]`.

But this can maybe be because I haven't really configured things like mod_wsgi and maybe Karp can't put any services up.

I upload the complete log file here: [20180324-debug.txt](https://github.com/spraakbanken/karp-backend/files/1844161/20180324-debug.txt).

My initial thought on server setup is to have Elasticsearch on the same server as the backend and frontend, when the testing phase is done and more lexical resources and users will be expected, then they will need to be separated.

**Comment by kristiank** [comment]
I am now exploring all thing that are being set up by Docker in karp-docker... Quite much to be done I see.

**Comment by kristiank** [comment]
When trying to publish my mode I get this error message:
```bash
python offline.py --publish_mode karp test
Publish karp_test as karp
remove ['{"remove": {"index":"karp_*", "alias":"karp"}}']
add ['{"add" : {"index": "karp_test", "alias": "karp"}}']
remove old aliases
No previous aliased indices, could not do remove any
['{"remove": {"index":"karp_*", "alias":"karp"}}']
Traceback (most recent call last):
  File "offline.py", line 20, in <module>
    upload.publish_group(group, suffix)
  File "/home/centos/spraakbanken/karp-backend/src/offline/upload_offline.py", line 251, in publish_group
    return es.indices.update_aliases('{"actions" : [%s]}' % ','.join(add_actions))
  File "/home/centos/spraakbanken/karp-backend/venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/centos/spraakbanken/karp-backend/venv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 403, in update_aliases
    params=params, body=body)
  File "/home/centos/spraakbanken/karp-backend/venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/centos/spraakbanken/karp-backend/venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 158, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x2239050>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x2239050>: Failed to establish a new connection: [Errno -2] Name or service not known)
```

**Comment by MalinAhlberg** [comment]
Om det är så att du använder en icke-docker-version av Karp, men fortfarande kör ES i Docker, så måste du confa Karpen att prata med ES via `localhost:8083` istället för `elasticsearch:9200`  (på ett eller flera ställen) i `config/modes.json`. Själva Karp fungerar ju i princip både i och utanför Docker på en gång, så det kan vara  lurigt att hålla ordning.

Testa också `curl localhost:8083` (lokalt utan Docker), och se om ES svarar. Om inte har något gått fel i byggandet av den. Kolla i så fall i `docker-compose logs`, alternativt bara starta om containern (`docker-compose restart elasticsearch`).

**Comment by kristiank** [comment]
Hej. Fick igang en lokal elasticsearch pa `curl localhost:8083` och jag ändrade `config/modes.json`. Nu är felmeddelandet detta:

```bash
$ sudo python offline.py --publish_mode karp test
Publish karp_test as karp
remove ['{"remove": {"index":"karp_*", "alias":"karp"}}']
add ['{"add" : {"index": "karp_test", "alias": "karp"}}']
remove old aliases
No previous aliased indices, could not do remove any
['{"remove": {"index":"karp_*", "alias":"karp"}}']
Traceback (most recent call last):
  File "offline.py", line 20, in <module>
    upload.publish_group(group, suffix)
  File "/var/www/html/src/offline/upload_offline.py", line 251, in publish_group
    return es.indices.update_aliases('{"actions" : [%s]}' % ','.join(add_actions))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 430, in update_aliases
    params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 110, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError
```

Kan jag hitta elasticsearch.yml config filen som används i Docker nanstans?

**Comment by MalinAhlberg** [comment]
Ok, bra. Kör du en ES i Docker så kommer man åt den via `elasticsearch:9200` inom docker-systemet och via `localhost:8083` utifrån.

Har indexet karp_test som du försöker publicera skapats som det skulle? Du kan testa `curl localhost:8083/_cat/indices` och  `curl localhost:8083/_cat/aliases`.

Inställningar till ES syns under environment i docker-compose.yml, det är inte så många.

**Comment by kristiank** [comment]
Thanks. This seems to be solved now.
