### ISSUE TITLE
SKBL sorting error "Şahindal"

### ISSUE THREAD

**Issue by anne17** [spraakbanken/karp-backend-v5#44]
"Şahindal, Fadime" is wrongly sorted under letter "A" in the skbl portal. This is due to the data that comes from elasticsearch.

Checking [the data from the backend](https://ws.spraakbanken.gu.se/ws/karp/v5/minientry?q=extended%7C%7Cand%7Cnamn%7Cexists&mode=skbllinks&show=name%2Curl&sort=sorteringsnamn.sort%2Csorteringsnamn.init%2Ctilltalsnamn.sort&size=10000&resource=skbl) it returns `"sort": [..., "a", ..."]` for "Şahindal, Fadime". It should be "s" instead of "a".

Right now we don't do any sorting of names in the skbl-portal, but we rely entirely on the sorting from elasticsearch. Therefore it would be better to fix this problem "at the source" instead of hacking the portal.

**Comment by kod-kristoff** [comment]
Issue moved to [spraakbanken/karp-backend-sb #31](https://github.com/spraakbanken/karp-backend-sb/issues/31) via [**ZenHub**](https://www.zenhub.com/)
